ServerEvents.recipes(event => {
    event.remove({id: "modern_industrialization:vanilla_recipes/compressor/diamond_from_coal"})
    event.remove({id: "modern_industrialization:compat/ae2/mixer/fluix"})
    event.remove({id: "modern_industrialization:compat/ae2/electrolyzer/ae2_certus_quartz_crystal_to_ae2_charged_certus_quartz_crystal"})
    event.remove({id: "modern_industrialization:compat/ae2/macerator/_c_gems_certus_quartz_to_ae2_certus_quartz_dust"})
    event.remove({id: "modern_industrialization:compat/ae2/calculation_processor"})
    event.remove({id: "modern_industrialization:compat/ae2/engineering_processor"})
    event.remove({id: "modern_industrialization:compat/ae2/logic_processor"})
    event.remove({id: "modern_industrialization:compat/ae2/printed_silicon"})
    event.remove({id: "modern_industrialization:compat/ae2/printed_silicon_from_ingot"})
    event.remove({id: "modern_industrialization:compat/ae2/printed_calculation_processor"})
    event.remove({id: "modern_industrialization:compat/ae2/printed_logic_processor"})
    event.remove({id: "modern_industrialization:compat/ae2/printed_engineering_processor"})
    event.remove({id: "modern_industrialization:vanilla_recipes/mixer/clay"})
})